# A headless service to create DNS records
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-controller-1
spec:
  replicas: 1
  selector:
    app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      hostname: str-1-zoo1
      containers:
      - name: str-1-zoo1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: str-1-zoo1 
        - name: ZOOKEEPER_SERVER_2
          value: str-2-zoo1
        - name: ZOOKEEPER_SERVER_3
          value: str-3-zoo1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-controller-2
spec:
  replicas: 1
  selector:
    app: zookeeper-2
  template:
    metadata:
      labels:
        app: zookeeper-2
    spec:
      hostname: str-2-zoo1
      containers:
      - name: str-2-zoo1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "2"
        - name: ZOOKEEPER_SERVER_1
          value: str-1-zoo1
        - name: ZOOKEEPER_SERVER_2
          value: str-2-zoo1
        - name: ZOOKEEPER_SERVER_3
          value: str-3-zoo1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-controller-3
spec:
  replicas: 1
  selector:
    app: zookeeper-3
  template:
    metadata:
      labels:
        app: zookeeper-3
    spec:
      hostname: str-3-zoo1
      containers:
      - name: str-3-zoo1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "3"
        - name: ZOOKEEPER_SERVER_1
          value: str-1-zoo1
        - name: ZOOKEEPER_SERVER_2
          value: str-2-zoo1
        - name: ZOOKEEPER_SERVER_3
          value: str-3-zoo1
