apiVersion: v1
kind: Service
metadata:
  name: med-evbmc
  labels:
    app: eventclient
spec:
  ports:
  - port: 4447
    name: med-evbmc-remote
    protocol: TCP
  - port: 9999
    protocol: TCP
    name: med-evbmc-ejb
  - port: 9990
    name: med-evbmc-admin
    protocol: TCP
  selector:
    app: eventclient
