apiVersion: v1
kind: Service
metadata:
  name: ldap-local
  labels:
    app: opendj
spec:
  ports:
  - port: 1636
    protocol: TCP
    name: opendj-unsecure
  - port: 1689
    protocol: TCP
    name: opendj-secure
  - port: 8447
    name: opendj-serv
    protocol: TCP
  - port: 4444
    name: admin-port
  selector:
    app: opendj

