apiVersion: v1
kind: ReplicationController
metadata:
  name: opendj
spec:
  template:
    metadata:
      labels:
        app: opendj
        tier: database
    spec:
      containers:
      - name: opendj
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/opendj:{{.Values.dockerTag}}
        resources:
          limits:
            memory: {{.Values.memLimit}}
            cpu: {{.Values.cpuLimit}}
        ports:
        - containerPort: 1636
        - containerPort: 1689
        - containerPort: 8447
        - containerPort: 4444

