kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: models-pvc
  labels:
    kubernetes.io/cluster-service: "false"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G

