apiVersion: v1
kind: Service
metadata:
  name: jms01
  labels:
    app: jms-server
spec:
  ports:
  - port: 4447
    protocol: TCP
    name: remoting
  - port: 9999
    protocol: TCP
    name: remote-ejb
  - port: 9990
    name: remote-admin
    protocol: TCP
  - port: 5445
    name: remote-jms
  selector:
    app: jms-server

