apiVersion: v1
kind: ReplicationController
metadata:
  name: parsers
spec:
  template:
    metadata:
      labels:
        app: parsers
    spec:
      containers:
      - name: parsers
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/{{.Values.imageName}}:{{.Values.dockerTag}}
        env:
         - name: DOMAIN
           value: {{.Values.pDNSDomain}}
         - name: NAMESPACE
           value: {{.Values.pNamespace}}
        ports:
        - containerPort: 10101

