imageRegistry: "armdocker.rnd.ericsson.se/proj_enm"
dockerTag: "16.15-1.30.88"
memLimit: "2Gi"
jvmXmx: "2048"
jvmXmn: "1g"
cpuLimit: "1024m"
dnsDomain: "default.svc.dekstroza.local"
pullPolicy: "Always"

