imageRegistry: "armdocker.rnd.ericsson.se/proj_bounded_application"
imageName: "schema-reg"
dockerTag: "17.1-1.33.2"
dnsDomain: "default.svc.dekstroza.local"
srNamespace: "default"
srDNSDomain: "dekstroza.local"
pullPolicy: "Always"
