apiVersion: v1
kind: Service
metadata:
  name: stream-terminator
  labels:
    app: stream-terminator
spec:
  ports:
  - port: 10101
    protocol: TCP
    name: st-port
  selector:
    app: stream-terminator

