apiVersion: v1
kind: ReplicationController
metadata:
  name: stream-terminator
spec:
  template:
    metadata:
      labels:
        app: stream-terminator
    spec:
      containers:
      - name: stream-terminator
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/{{.Values.imageName}}:{{.Values.dockerTag}}
        env:
         - name: DOMAIN
           value: {{.Values.stDNSDomain}}
         - name: NAMESPACE
           value: {{.Values.stNamespace}}
        ports:
        - containerPort: 10101

