apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-controller-1
spec:
  replicas: 1
  selector:
    app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      hostname: str-1-kafka1
      containers:
      - name: str-1-kafka1
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/{{.Values.imageName}}:{{.Values.dockerTag}}
        ports:
        - containerPort: 9092
        - containerPort: 20101
          name: JMX
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-controller-2
spec:
  replicas: 1
  selector:
    app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      hostname: str-2-kafka1
      containers:
      - name: str-2-kafka1
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/{{.Values.imageName}}:{{.Values.dockerTag}}
        ports:
        - containerPort: 9092
        - containerPort: 20101
          name: JMX
