apiVersion: v1
kind: Service
metadata:
  name: str-1-kafka1
  labels:
    app: kafka-1
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  - port: 20101
    name: JMX
    protocol: TCP
  selector:
    app: kafka-1
---
apiVersion: v1
kind: Service
metadata:
  name: str-2-kafka1
  labels:
    app: kafka-2
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  - port: 20101
    name: JMX
    protocol: TCP
  selector:
    app: kafka-2
