apiVersion: v1
kind: ReplicationController
metadata:
  name: decoded-forwarder-controller-1
spec:
  replicas: 1
  selector:
    app: decoded-forwarder-1
  template:
    metadata:
      labels:
        app: decoded-forwarder-1
    spec:
      hostname: str-1-dfwd1
      containers:
      - name: str-1-dfwd1
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/{{.Values.imageName}}:{{.Values.dockerTag}}
        ports:
         - containerPort: 20101
           name: JMX
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: decoded-forwarder-controller-2
spec:
  selector:
    app: decoded-forwarder-2
  template:
    metadata:
      labels:
        app: decoded-forwarder-2
    spec:
      hostname: str-2-dfwd1
      containers:
      - name:  str-2-dfwd1
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/{{.Values.imageName}}:{{.Values.dockerTag}}
        ports:
         - containerPort: 20101
           name: JMX


