apiVersion: v1
kind: Service
metadata:
  name: str-1-dfwd1
  labels:
    app: decoded-forwarder-1
spec:
  ports:
  - port: 20101
    name: JMX
    protocol: TCP
  selector:
    app: decoded-forwarder-1
---
apiVersion: v1
kind: Service
metadata:
  name: str-2-dfwd1
  labels:
    app: decoded-forwarder-2
spec:
  ports:
  - port: 20101
    name: JMX
    protocol: TCP
  selector:
    app: decoded-forwarder-2
