apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  labels:
    app: schema-registry
spec:
  ports:
  - port: 10101
    protocol: TCP
    name: sr-port
  selector:
    app: schema-registry

