apiVersion: v1
kind: ReplicationController
metadata:
  name: schema-registry
spec:
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/{{.Values.imageName}}:{{.Values.dockerTag}}
        env:
         - name: DOMAIN
           value: {{.Values.srDNSDomain}}
         - name: NAMESPACE
           value: {{.Values.srNamespace}}
        ports:
        - containerPort: 10101

