apiVersion: v1
kind: Service
metadata:
  name: policy
  labels:
    app: policy
spec:
  ports:
  - port: 4447
    name: policy-remote
    protocol: TCP
  - port: 9999
    protocol: TCP
    name: policy-ejb
  - port: 9990
    name: policy-admin
    protocol: TCP
  selector:
    app: policy
