apiVersion: v1
kind: Service
metadata:
  name: secserv
  labels:
    app: secserv
spec:
  ports:
  - port: 4447
    name: secserv-remote
    protocol: TCP
  - port: 9999
    protocol: TCP
    name: secserv-ejb
  - port: 9990
    name: secserv-admin
    protocol: TCP
  - port: 22
    name: ssh-port
  selector:
    app: secserv
