apiVersion: v1
kind: ReplicationController
metadata:
  name: stream-terminator-controller-1
spec:
  replicas: 1
  selector:
    app: stream-terminator-1
  template:
    metadata:
      labels:
        app: stream-terminator-1
    spec:
      hostname: str-1-msstr1
      containers:
      - name: str-1-msstr1
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/{{.Values.imageName}}:{{.Values.dockerTag}}
        ports:
         - containerPort: 10101
           name: st-port
         - containerPort: 20101
           name: JMX
         - containerPort: 63111
         - containerPort: 63109
         - containerPort: 63110
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: stream-terminator-controller-2
spec:
  replicas: 1
  selector:
    app: stream-terminator-2
  template:
    metadata:
      labels:
        app: stream-terminator-2
    spec:
      hostname: str-2-msstr1
      containers:
      - name: str-2-msstr1
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/{{.Values.imageName}}:{{.Values.dockerTag}}
        ports:
         - containerPort: 10101
           name: st-port
         - containerPort: 20101
           name: JMX
         - containerPort: 63111
         - containerPort: 63109
         - containerPort: 63110


