apiVersion: v1
kind: Service
metadata:
  name: str-1-msstr1
  labels:
    app: stream-terminator-1
spec:
  ports:
  - port: 10101
    protocol: TCP
    name: st-port
  - port: 20101
    name: JMX
    protocol: TCP
  - port: 63111
    protocol: TCP
  - port: 63109
    protocol: UDP
  - port: 63110
    protocol: UDP
  selector:
    app: stream-terminator-1
---
apiVersion: v1
kind: Service
metadata:
  name: str-2-msstr1
  labels:
    app: stream-terminator-2
spec:
  ports:
  - port: 10101
    protocol: TCP
    name: st-port
  - port: 20101
    name: JMX
    protocol: TCP
  - port: 63111
    protocol: TCP
  - port: 63109
    protocol: UDP
  - port: 63110
    protocol: UDP
  selector:
    app: stream-terminator-2
