apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      containers:
      - name: postgres
        imagePullPolicy: {{.Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/postgres:{{.Values.dockerTag}}
        env:
         - name: DOMAIN
           value: {{.Values.dnsDomain}}
        resources:
          limits:
            memory: {{.Values.memLimit}}
            cpu: {{.Values.cpuLimit}}
        ports:
        - containerPort: 3306
        - containerPort: 5432

