apiVersion: v1
kind: Service
metadata:
  name: postgresql01
  labels:
    app: postgres
spec:
  ports:
  - port: 3306
    name: postgres
    protocol: TCP
  - port: 5432
    name: psql-port
    protocol: TCP
  selector:
    app: postgres

